apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-consumer
  namespace: othmane-achour
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/consumer-ao-2024:othmane-achour
        env:
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq"
        - name: REDIS_HOST
          value: "svc-redis"