apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-front
  namespace: othmane-achour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${REGISTRY}/frontend:latest
        env:
        - name: API_URL
          value: "http://svc-api"