apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-front
  namespace: othmane-achour
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/frontend-ao-2024:othmane-achour
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
        ports:
          - name: http
            containerPort: 80
            protocol: TCP