apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-api
  namespace: othmane-achour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ${REGISTRY}/api:latest
        env:
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq"
        - name: REDIS_HOST
          value: "svc-redis"