apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-api
  namespace: othmane-achour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-ao-2024:othmane-achour
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: REDIS_HOST
          value: "redis-service"